services:
  - type: web
    name: silurianweather
    runtime: docker
    plan: free

    # These two tell Render how to build your image
    dockerfilePath: ./Dockerfile
    dockerContext: .

    envVars:
      - key: DB_DRIVER
        value: sqlite

    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
