services:
  - type: web
    name: silurianweather
    runtime: php        
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: DB_DRIVER
        value: sqlite
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
